export const UserActionType = {
    GOOGLE_SIGNIN_START: 'GOOGLE_SIGNIN_START',
    SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
    SIGNIN_ERROR: 'SIGNIN_ERROR',
    EMAIL_SIGNIN_START: 'EMAIL_SIGNIN_START',
    GET_CURRENT_SESSION: 'GET_CURRENT_SESSION',
    SIGNOUT_START: 'SIGNOUT_START',
    SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
    SIGNOUT_ERROR: 'SIGNOUT_ERROR',
    SIGNUP_START: 'SIGNUP_START'
}